//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Filmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmy()
        {
            this.Cennik = new ObservableCollection<Cennik>();
            this.Nośnik = new ObservableCollection<Nośnik>();
            this.Reklamacje = new ObservableCollection<Reklamacje>();
            this.Wypożyczenia = new ObservableCollection<Wypożyczenia>();
        }
    
        public int IDFilmu { get; set; }
        public string Tytuł { get; set; }
        public string Gatunek { get; set; }
        public string Reżyser { get; set; }
        public int Rok { get; set; }
        public string Kraj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Cennik> Cennik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Nośnik> Nośnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reklamacje> Reklamacje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Wypożyczenia> Wypożyczenia { get; set; }
    }
}
