//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Nośnik
    {
        public int IDFilmu { get; set; }
        public bool BluRay { get; set; }
        public bool DVD { get; set; }
        public bool VHS { get; set; }
    
        public virtual Filmy Filmy { get; set; }
    }
}
